### PR TITLE
Replace deprecated Session with RequestStack, for Symfony 5.3

### PR DESCRIPTION
**Pull request by samwilson**
More info:
https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation

Bug: https://phabricator.wikimedia.org/T311024

### CODE REVIEW

**Review by theresnotime — COMMENTED** [review]
**+1** — lgtm, checks pass but _not tested_

**Review by MusikAnimal — APPROVED** [review]
I was going to say that in this bundle, we should make sure not to use `RequestStack::getSession()` since that isn't a thing in Symfony 4, but looks like you're always getting the session from the `Request` object, hence we should be good :)

**Comment by samwilson** [comment]
> I was going to say that in this bundle, we should make sure not to use `RequestStack::getSession()` since that isn't a thing in Symfony 4, but looks like you're always getting the session from the `Request` object, hence we should be good :)

That's a good point, but yeah it should be okay. I'm also currently looking at upgrading SVG Translate from Symfony 4 anyway (which I guess just leaves XTools?).

**Comment by MusikAnimal** [comment]
XTools is stuck on 4.4 until we (or I, really) figure out what to do with `XtoolsController`. In previous attempts I was unsuccessful in getting it to extend `AbstractController` instead the older `Controller` class without it causing major breakage. Maybe Inspiration Week is a good time to take another look, though!

XTools doesn't use the bundle anyway, due to #25

**Pull request merged**
