### PR TITLE
Allow client to specify a URL to redirect to after logging in

### PR DESCRIPTION
**Pull request by MusikAnimal**

### CODE REVIEW

**Review by aezell — APPROVED** [review]
Untested but LGTM.

**Comment by samwilson** [comment]
This looks good to me (although I also haven't yet tested it). The only thing I can think of is maybe adding to the docs something about the fact that any callback URL must be prefixed with the URL recorded in the consumer on Meta (and the consumer callback must have that 'prefix' option set). I'm not sure what happens when you give it a completely different URL, but I think it'll error out before redirecting back from the wiki.

**Comment by MusikAnimal** [comment]
> This looks good to me (although I also haven't yet tested it). The only thing I can think of is maybe adding to the docs something about the fact that any callback URL must be prefixed with the URL recorded in the consumer on Meta (and the consumer callback must have that 'prefix' option set). I'm not sure what happens when you give it a completely different URL, but I think it'll error out before redirecting back from the wiki.

I've added a bit more information in the README.

This change is live at https://tools.wmflabs.org/global-search, for instance https://tools.wmflabs.org/global-search/?q=Ezell (I manually changed ToolforgeBundle's AuthController)

**Review by samwilson — APPROVED** [review]

**Comment by samwilson** [comment]
Thanks for this!

I've released 0.15.0 with it.

**Pull request merged**
