### PR TITLE
Fix typo and slight error in readme

### PR DESCRIPTION
**Pull request by samwilson**

### CODE REVIEW

**Review by aezell — APPROVED** [review]

**Comment by samwilson** [comment]
Thanks Alex! That was quick. :)

**Comment by aezell** [comment]
You caught me at the right time.

**Comment by MusikAnimal** [comment]
I was just about to fix the same typo!!! I'm using ToolforgeBundle in a new project, https://github.com/MusikAnimal/global-search

**Comment by samwilson** [comment]
Cool! Don't forget to add it to the list in the readme here. :-)

**Pull request merged**
